server:
  port: 8081
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          default-label: config-service
          uri: https://github.com/jcarlostoso/springboot-desde-cero
          search-paths: config-data




